---
- name: Listen for events on a webhook from Dynatace
  hosts: all
  sources:
    - name: Listen for alerts from Dynatrace
      eda.builtin.webhook:
        host: 0.0.0.0
        port: 4997

  rules:
    - name: mariabd fail
      condition: event.payload.eventData['event.name'] == "Service is in an undesirable state"
      action:
        run_workflow_template:
          name: "mariadb remediation"
          organization: "Default"
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.eventData['host.name'][0] }}"
