---
- name: Enviar POST a webhook con JSON usando Ansible
  hosts: localhost
  gather_facts: false

  tasks:
      - name: notificar playbook en proceso
      ansible.builtin.uri:
        url: "{{ _url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: Lighspeed ha generado el siguiente Playbook
                
        validate_certs: false
        return_content: true
      register: response.0
    - name: Enviar texto a webhook chatops
      ansible.builtin.uri:
        url: "{{ _url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: 
                "{{ generated_playbook_out }}"
                
        validate_certs: false
        return_content: true
      register: response.1
    - name: Enviar texto a webhook chatops
      ansible.builtin.uri:
        url: "{{ _url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: si desea ejecutarlo escriba resolver
                
        validate_certs: false
        return_content: true
      register: response.2
      
    - name: Mostrar respuesta del servidor
      ansible.builtin.debug:
        var: response1.content
