---
- name: Enviar POST a webhook con JSON usando Ansible
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Notificar playbook en proceso
      ansible.builtin.uri:
        url: "{{ _url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "Lightspeed ha generado el siguiente Playbook"
        validate_certs: false
        return_content: true
      register: response_0

    - name: Enviar playbook a chat en bloque YAML
      ansible.builtin.uri:
        url: "{{ _url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "{{ '```yaml\n' ~ generated_playbook_out ~ '\n```' }}"
        validate_certs: false
        return_content: true
      register: response_1

    - name: Solicitar respuesta a chat
      ansible.builtin.uri:
        url: "{{ _url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "Ansible Automation Platform esta ejecutando la remediación"
        validate_certs: false
        return_content: true
      register: response_2


    - name: Solicitar respuesta a chat
      ansible.builtin.uri:
        url: "{{ _url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "El servicio de Mariadb ya se encuentra operativo"
        validate_certs: false
        return_content: true
      register: response_2


    - name: Mostrar respuesta del servidor
      ansible.builtin.debug:
        var: response_1
