---
- name: Buscar primera unknown option en log de MariaDB
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Obtener primera coincidencia del error unknown option
      ansible.builtin.shell: >
        grep "unknown option" /var/log/mariadb/mariadb.log |
        head -n 1 |
        grep -oP "'--\K[^']+"
      register: mysql_unknown_option
      changed_when: false
      failed_when: false

    - name: Mostrar opcion encontrada
      ansible.builtin.debug:
        msg: "La opcion desconocida encontrada es: {{ mysql_unknown_option.stdout }}"
      when: mysql_unknown_option.stdout != ""
    - name: solicita resolucion a la IA
      ansible.builtin.set_stats:
        data: 
          mysql_unknown_option: "{{ mysql_unknown_option.stdout }}"
