---
- name: Filtrar errores de MariaDB
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Obtener log disponible de MariaDB/MySQL o listar datadir
      ansible.builtin.shell: |
        tail -n 100 /var/log/mariadb/mariadb.log 2>/dev/null 
      register: mariadb_debug
      changed_when: false
      failed_when: false

    - name: Filtrar solo lineas con error de mariadbd
      ansible.builtin.set_fact:
        mariadb_error_lines: >-
          {{
            mariadb_debug.stdout_lines
            | select('search', '\[ERROR\] /usr/libexec/mariadbd:')
            | list
          }}

    - name: Mostrar lineas filtradas
      ansible.builtin.debug:
        var: mariadb_error_lines


